@startuml

class AuthenticationActivity
class HomeActivity
class ProfileActivity
class SignInActivity

class UserProfile {
    username : String
    firstName : String
    lastName : String
    UserProfile(username:String)
    UserProfile(username:String,firstName:String,lastName:String)
}

class MoodEvent {
    Coordinate location
    DateTime dateTime;
    String remark;
    Image image;
    SocialSituation situation
    EmotionType emotion
    MoodEvent(dateTime:DateTime,emotion:Emotion)
}

class Emotion {
    String imageResourceName
    String emotionName
    Emotion(imageResourceName:String,emotionName:String)
}

HomeActivity *-- MapFragment
HomeActivity o-- MoodListFragment
HomeActivity o-- MoodAdapter
HomeActivity *-- SearchFragment
HomeActivity *-- FollowingFragment
HomeActivity o-- FilterFragment
HomeActivity o-- DetailsFragment

abstract class Filter <<android>>
class FilterFragment

ProfileActivity -- UserProfile
ProfileActivity -- MoodListFragment
ProfileActivity -- FilterFragment

FollowingFragment -- UserProfile
SearchFragment -- UserProfile

'MapFragment -- MoodAdapter
MapFragment -- MoodFilter

MoodListFragment -- MoodAdapter

DetailsFragment -- MoodEvent

class Coordinate {
    latitude : double
    longitude : double
    Coordinate(latitude:double,longitude:double)
}

MoodEvent -- Coordinate

class MoodAdapter {
    getFilter : MoodFilter
}

MoodAdapter -- MoodFilter

class MoodFilter {
    filter(filterSequence : String}
}

abstract class Filter <<android>> 
Filter <|-- MoodFilter

UserProfile -- MoodAdapter

class ArrayAdapter <<android>>
ArrayAdapter <|-- MoodAdapter

MoodAdapter -- MoodEvent
interface Filterable <<android>>
Filterable <|-- MoodAdapter

MoodEvent -- Emotion

enum EmotionType
EmotionType -- Emotion

@enduml
