@startuml

skinparam linetype ortho

package "View" {

    package "Activities" <<Rectangle>> {

        class AuthenticationActivity

        class SignInActivity

        class HomeActivity

        class ProfileActivity {
            profile : Profile
        }

        AuthenticationActivity "1" -- "1" HomeActivity : "Transitions to\nHomeActivity\nif logged in."
        AuthenticationActivity "1" -- "1" SignInActivity : "Transitions to\nSignInActivity\nif not logged in."
        SignInActivity "1" -- "1" HomeActivity : "Transitions to\nHomeActivity\nonce logged in."
        HomeActivity -- ProfileActivity: "Transitions to\nHomeActivity\n/\nProfileActivity."
    }

    package "Fragments" <<Rectangle>> {

        class MoodListFragment {
            dataList : List<MoodEvent> 
            dataAdapter : ArrayAdapter<MoodEvent> 
            listView : ListView

            applyFilter(filter : String)
        }

        class SearchFragment {
            profileList : ProfileListFragment
            currentSearch : String
        }

        class AddFragment {
        }

        class FollowingFragment {
            profileList : ProfileListFragment
        }

        class DetailsFragment {
            mood : MoodEvent
            editingEnabled : boolean
        }

        class ProfileListFragment {
            listView : ListView
            dataList : List<Profile>

            applyFilter(filter : String)
        }

        HomeActivity "1" *-- "1" MapFragment : "Transitions to\nMapFragment."
        HomeActivity "1" o-- "1" MoodListFragment : "Transitions to\nMoodListFragment."
        HomeActivity "1" *-- "1" SearchFragment : "Transitions to\nSearchFragment."
        HomeActivity "1" *-- "1" AddFragment : "Transitions to\nAddFragment."
        HomeActivity "1" *-- "1" FollowingFragment : "Transitions to\nFollowingFragment."
        HomeActivity "1" o-- "1" FilterFragment : "Transitions to\nFilterFragment."
        HomeActivity "1" o-- "1" DetailsFragment : "Transitions to\nDetailsFragment."
        ProfileActivity "1" o-- "1" MoodListFragment : "Transitions to\nMoodListFragment."
        ProfileActivity "1" o-- "1" FilterFragment : "Transitions to\nFilterFragment."

        SearchFragment "1" o-- "2" ProfileListFragment : "SearchFragment\nlists matching\nprofiles via\nProfileListFragment."
        FollowingFragment "1" o-- "1" ProfileListFragment : "FollowingFragment\nlists followees via\nProfileListFragment."

    }

}

package "Android API" <<Rectangle>> {

    interface Filterable
    interface Filter
    abstract class ArrayAdapter
}

package "Control" <<Rectangle>> {

    class MoodAdapter {
        dataList : List<MoodEvent>
        getFilter() : MoodFilter
    }

    class ProfileAdapter {
        dataList : List<MoodEvent>
        getFilter() : ProfileFilter
    }

    class MoodFilter {
        filter(constraint : CharSequence) <<override>>
    }

    class ProfileFilter {
        filter(constraint : CharSequence) <<override>>
    }
    
    Filterable "1" <|-- "1" MoodAdapter : "MoodAdapter uses\nFilterable\nto filter moods."
    ArrayAdapter "1" <|-- "1" MoodAdapter : "MoodEvent implements\nArrayAdapter."

    Filterable "1" <|-- "1" ProfileAdapter : "ProfileAdapter uses\nFilterable\nto filter profiles."
    ArrayAdapter "1" <|-- "1" ProfileAdapter : "ProfileEvent implements\nArrayAdapter."
    
    Filter "1" <|-- "1" MoodFilter : "MoodFilter implements\nFilter."
    Filter "1" <|-- "1" ProfileFilter : "ProfileFilter implements\nFilter."

    ProfileAdapter "1" -- "1" ProfileFilter : "ProfileAdapter uses\nProfileFilter\nto filter profiles."
    MoodAdapter "1" -- "1" MoodFilter : "MoodAdapter uses\nMoodFilter\nto filter moods."
}

MapFragment "1" -- "1" MoodAdapter : "MapFragment\ndisplays the moods\nfrom MoodAdapter."
MoodListFragment "1" -- "1" MoodAdapter : "MoodListFragment\ndisplays the moods\nfrom MoodAdapter."
MoodListFragment "1" -- "1" MoodFilter : "MoodListFragment uses\nFilterable\nto filter moods."

ProfileListFragment "1" o-- "1" ProfileAdapter : "ProfileListFragment\ndisplays the profiles\nfrom ProfileAdapter."
ProfileListFragment "1" -- "1" ProfileFilter : "ProfileListFragment uses\nProfileFilter\nto filter profiles."

MapFragment "1" -- "1" MoodFilter

package "Model" <<Rectangle>> {

    class UserProfile {
        UserProfile(username : String)
        UserProfile(username : String, firstName : String, lastName : String)
    }

    class MoodEvent {
        location : Location 
        dateTime : DateTime 
        remark : String 
        image : Image 
        situation : SocialSituation 
        emotion : Emotion
        MoodEvent(dateTime:DateTime,emotion:Emotion)
    }

    class Emotion {
        -emotions : static Map<String, Emotion>
        +get(name : String) : static Emotion

        -imageResource : String 
        -name : String 
    }

    class SocialSituation {
        -situations : static Map<String, SocialSituation>
        +get(key : String) : static SocialSituation

        -name : String
        -SocialSituation(name : String)
    }

    class Location {
        -latitude : double
        -longitude : double

        +Location(latitude:double,longitude:double)

        +getLatitude() : double
        +getLongitude() : double
    }

    class Profile {
        -username : final String
        -firstName : String
        -lastName : String

        +Profile(username : String)
        +Profile(username : String, firstName : String, lastName : String)
    }

    class PublicProfile {
        -following : boolean

        +PublicProfile(username : String)
        +PublicProfile(username : String, firstName : String, lastName : String)
    }

    package "Java API" <<Rectangle>> {
    class DateTime
    }   

    MoodEvent "1" o-- "1" Emotion : "Emotion is\ncontained by\nMoodEvent."
    MoodEvent "1" *-- "1" Location : "Location is\ncontained by\nMoodEvent."
    MoodEvent "1" o-- "1" SocialSituation : "SocialSituation is\ncontained by\nMoodEvent."
    MoodEvent "1" *-- "1" DateTime : "DateTime is\ncontained by\nMoodEvent."

    Profile "1" <|-- "1" UserProfile : "UserProfile\nis a kind of\nProfile"
    Profile "1" <|-- "1" PublicProfile : "PublicProfile\nis a kind of\nProfile"

}

MoodAdapter "1" -- "0..*" MoodEvent : "MoodAdapter\nconnects the\nMoodEvents's\nto the data set."
ProfileAdapter "1" -- "0..*" Profile : "ProfileAdapter\nconnects the\nProfile's\nto the data set."

MoodFilter "1" -- "1" MoodEvent : "MoodEvent\nuses\nMoodFilter."
ProfileFilter "1" -- "0..*" Profile : "Profile\nuses\nProfileFilter."

DetailsFragment "1" -- "1" MoodEvent : "Details\ndisplays the details\nof a MoodEvent."

@enduml
